/* ───────── DATA ───────── */
export const TOPICS = [
  { id: 'mat-ngu', icon: '🌙', vi: 'Mất Ngủ & Đau Đầu', en: 'Insomnia & Headaches', descVi: 'Phương pháp phi thuyền chữa mất ngủ', descEn: 'Spaceship method for insomnia', count: 12 },
  { id: 'tam-linh', icon: '✦', vi: 'Tâm Linh & Tôn Giáo', en: 'Spirituality & Religion', descVi: 'Ánh sáng vượt qua mọi tôn giáo', descEn: 'Light beyond all religions', count: 18 },
  { id: 'suc-khoe', icon: '❤', vi: 'Sức Khỏe Cơ Thể', en: 'Body Health', descVi: 'Năng lượng chữa lành cơ thể', descEn: 'Energy healing for the body', count: 15 },
  { id: 'vu-tru', icon: '◎', vi: 'Y Học Vũ Trụ', en: 'Cosmic Medicine', descVi: 'Nguyên lý vũ trụ trong y học', descEn: 'Cosmic principles in medicine', count: 22 },
  { id: 'tri-tue', icon: '◈', vi: 'Trí Tuệ Việt Nam', en: 'Vietnamese Wisdom', descVi: 'Kho tàng trí tuệ người Việt', descEn: 'Treasury of Vietnamese wisdom', count: 10 },
  { id: 'thuc-hanh', icon: '△', vi: 'Thực Hành', en: 'Practice', descVi: 'Bài tập thực hành hàng ngày', descEn: 'Daily practice exercises', count: 8 },
]

export const DEFAULT_ARTICLES = [
  {
    id: 'default-1', topic: 'mat-ngu', date: '2026-01-15', tag: { vi: 'Mất Ngủ', en: 'Insomnia' },
    vi: {
      title: 'Phi thuyền đưa linh hồn đi vào vũ trụ du lịch và an nghỉ ở khách sạn thiên đường',
      question: 'Con bị đau đầu mất ngủ 4 năm, uống thuốc tây thì ngủ được, không uống là thức trắng.',
      summary: 'Phương pháp phi thuyền: nhắm mắt, nhìn ra ánh sáng mờ ảo, phóng ra ngoài vũ trụ. Lắc qua lắc lại, du lịch không gian, tìm đến khách sạn thiên đường ánh sáng. Nằm trong phòng ngủ trắng có hoa thơm, sáng thức dậy đau đầu từ từ biến mất.',
      body: 'Phương pháp phi thuyền là một kỹ thuật thiền định đặc biệt. Bạn nhắm mắt lại, tưởng tượng mình đang ngồi trong một phi thuyền ánh sáng. Nhìn ra phía trước, bạn thấy ánh sáng mờ ảo lung linh. Phi thuyền bắt đầu di chuyển, lắc nhẹ qua lại như đang bay qua các vì sao.\n\nBạn du lịch qua không gian vũ trụ bao la, qua các thiên hà lấp lánh. Cuối cùng, phi thuyền đưa bạn đến khách sạn thiên đường - một nơi tràn ngập ánh sáng vàng ấm áp.\n\nBạn bước vào phòng ngủ trắng tinh khiết, có hoa thơm ngát. Nằm xuống giường mềm mại, bạn cảm nhận năng lượng ánh sáng chữa lành từ từ thấm vào cơ thể. Sáng hôm sau thức dậy, đau đầu từ từ biến mất.',
    },
    en: {
      title: 'Spaceship carrying the soul into cosmic travel and rest at the paradise hotel of light',
      question: "I've had headaches and insomnia for 4 years. Western medicine helps me sleep, without it I stay up all night.",
      summary: 'The spaceship method: close your eyes, look toward dim light, project outward into the universe. Sway gently, travel through space, find the paradise hotel of light. Rest in a white room with fragrant flowers, wake up and headaches gradually disappear.',
      body: 'The spaceship method is a special meditation technique. Close your eyes and imagine sitting in a spaceship of light. Looking ahead, you see shimmering dim light. The spaceship begins to move, swaying gently as if flying past stars.\n\nYou travel through the vast cosmos, past sparkling galaxies. Finally, the spaceship brings you to the paradise hotel - a place overflowing with warm golden light.\n\nYou enter a pure white room filled with fragrant flowers. Lying on the soft bed, you feel healing light energy slowly permeating your body. The next morning when you wake, headaches gradually disappear.',
    },
  },
  {
    id: 'default-2', topic: 'tam-linh', date: '2026-01-18', tag: { vi: 'Tâm Linh', en: 'Spirituality' },
    vi: {
      title: 'Thế giới loài người muốn có hòa bình thì không nên phân chia sắc tộc, tôn giáo',
      question: 'Con theo đạo Công Giáo. Nhắm mắt nhìn sâu vào tim thì tim đập nhanh, thấy hình ảnh Chúa Giêsu.',
      summary: 'Công giáo hay Phật giáo đều chung mục đích. Đừng niệm Chúa hay Phật vào tâm, hãy nhìn ra ánh sáng. Chúa nói \'Ta là ánh sáng\' thì nhìn ánh sáng, không nhìn tượng. Trái tim cần tự do, hấp thu năng lượng từ ánh sáng.',
      body: 'Tất cả các tôn giáo trên thế giới đều hướng đến một mục đích chung: giải thoát con người khỏi khổ đau và đưa tâm hồn đến nơi an lạc.\n\nChúa Giêsu nói "Ta là ánh sáng thế gian." Đức Phật cũng dạy về ánh sáng giác ngộ. Vậy thì thay vì niệm danh hiệu, hãy nhìn thẳng vào ánh sáng - nguồn gốc chung của mọi tôn giáo.\n\nKhi bạn nhắm mắt và nhìn ra ánh sáng thay vì nhìn vào trong, trái tim được tự do. Nó không còn bị giam trong khuôn khổ tôn giáo nào. Trái tim hấp thu năng lượng trực tiếp từ ánh sáng vũ trụ, và đó chính là con đường hòa bình thật sự.',
    },
    en: {
      title: 'For world peace, humanity should not divide by race or religion',
      question: "I'm Catholic. When I close my eyes and look deep into my heart, it beats fast and I see Jesus.",
      summary: "Catholicism and Buddhism share the same purpose. Don't recite Christ or Buddha into your heart, look outward to light. Christ said 'I am the light' so look at light, not statues. The heart needs freedom, absorbing energy from light.",
      body: 'All religions in the world share a common purpose: to free humanity from suffering and guide the soul to peace.\n\nJesus Christ said "I am the light of the world." The Buddha also taught about the light of enlightenment. So instead of reciting names, look directly at the light - the common origin of all religions.\n\nWhen you close your eyes and look outward toward light instead of inward, the heart becomes free. It is no longer confined within any religious framework. The heart absorbs energy directly from cosmic light, and that is the true path to peace.',
    },
  },
  {
    id: 'default-3', topic: 'vu-tru', date: '2026-01-22', tag: { vi: 'Vũ Trụ', en: 'Cosmic' },
    vi: {
      title: 'Nguyên lý đốt rác não và chuyển đổi năng lượng vũ trụ',
      question: 'Tại sao con hay bị đau đầu và stress?',
      summary: 'Hai con mắt thịt hút thông tin vào não giữa. Não giữa đốt rác thông tin, chuyển thành năng lượng. Không đốt được thì rác chất đống, não nóng như hiệu ứng nhà kính. Phi thuyền giúp đốt rác, giải phóng trí tuệ.',
      body: 'Mỗi ngày, hai con mắt của bạn liên tục hút thông tin từ thế giới bên ngoài vào não. Thông tin này được chuyển đến não giữa - trung tâm xử lý của ý thức.\n\nNão giữa có nhiệm vụ "đốt rác" - tức là phân loại, xử lý và chuyển đổi thông tin thành năng lượng hữu ích. Giống như một lò đốt rác hoạt động hiệu quả.\n\nNhưng khi bạn tiếp nhận quá nhiều thông tin tiêu cực, lo âu, stress - lò đốt quá tải. Rác thông tin chất đống trong não, tạo ra nhiệt như hiệu ứng nhà kính. Đó là nguyên nhân đau đầu và mất ngủ.\n\nPhương pháp phi thuyền giúp kích hoạt lại lò đốt rác của não. Khi bạn nhắm mắt và phóng ra ngoài vũ trụ, bạn ngừng hút rác vào. Đồng thời, năng lượng vũ trụ giúp đốt sạch rác tồn đọng, giải phóng trí tuệ.',
    },
    en: {
      title: 'The principle of brain waste burning and cosmic energy conversion',
      question: 'Why do I always have headaches and stress?',
      summary: "Two physical eyes absorb information into the mid-brain. The mid-brain burns information waste, converting it to energy. When it can't burn, waste piles up, the brain heats like a greenhouse effect. The spaceship method helps burn waste and release wisdom.",
      body: 'Every day, your two eyes continuously absorb information from the outside world into the brain. This information is transferred to the mid-brain - the processing center of consciousness.\n\nThe mid-brain has the task of "burning waste" - that is, sorting, processing, and converting information into useful energy. Like an efficient waste incinerator.\n\nBut when you receive too much negative information, anxiety, stress - the incinerator overloads. Information waste piles up in the brain, generating heat like the greenhouse effect. That is the cause of headaches and insomnia.\n\nThe spaceship method helps reactivate the brain\'s waste incinerator. When you close your eyes and project outward into the universe, you stop absorbing waste. At the same time, cosmic energy helps burn accumulated waste, releasing wisdom.',
    },
  },
]

export const T = {
  vi: {
    siteName: 'Bất Tử Đạo',
    siteTagline: 'Trí Tuệ Người Việt Nam',
    heroTitle: 'Phi Thuyền Trí Tuệ',
    heroSub: 'Khám phá ánh sáng bên trong bạn — hành trình chữa lành từ trí tuệ Việt Nam ngàn đời',
    heroCta: 'Khám Phá Ngay',
    topicsTitle: 'Chủ Đề',
    articlesTitle: 'Bài Viết Mới',
    articles: 'bài viết',
    readMore: 'Đọc tiếp',
    watchVideo: 'Xem video',
    back: '← Quay lại',
    videoPlaceholder: 'Video sẽ được cập nhật',
    searchTitle: 'Tìm Kiếm',
    searchPlaceholder: 'Tìm theo tiêu đề, câu hỏi...',
    noResults: 'Không tìm thấy kết quả',
    contactTitle: 'Liên Hệ',
    contactName: 'Họ và tên',
    contactEmail: 'Email',
    contactMsg: 'Nội dung tin nhắn',
    contactSend: 'Gửi Tin Nhắn',
    contactThanks: 'Cảm ơn bạn! Tin nhắn đã được gửi.',
    footer: '© 2026 Bất Tử Đạo. Nội dung mang tính chia sẻ cá nhân, không thay thế tư vấn y khoa chuyên nghiệp.',
    navHome: 'Trang chủ',
    navTopics: 'Chủ đề',
    navSearch: 'Tìm kiếm',
    navContact: 'Liên hệ',
    menuOpen: 'Menu',
    // New translations
    share: 'Chia sẻ',
    copyLink: 'Sao chép link',
    copied: 'Đã sao chép!',
    comments: 'Bình luận',
    commentName: 'Tên của bạn',
    commentText: 'Viết bình luận...',
    commentSend: 'Gửi',
    commentEmpty: 'Chưa có bình luận nào. Hãy là người đầu tiên!',
    adminTitle: 'Quản Lý Bài Viết',
    adminLogin: 'Đăng nhập Admin',
    adminEmail: 'Email',
    adminPassword: 'Mật khẩu',
    adminSignIn: 'Đăng nhập',
    adminSignOut: 'Đăng xuất',
    adminAdd: 'Thêm bài viết',
    adminEdit: 'Sửa',
    adminDelete: 'Xoá',
    adminSave: 'Lưu',
    adminCancel: 'Huỷ',
    adminTopic: 'Chủ đề',
    adminTag: 'Tag',
    adminDate: 'Ngày',
    adminTitleVi: 'Tiêu đề (VI)',
    adminTitleEn: 'Tiêu đề (EN)',
    adminQuestionVi: 'Câu hỏi (VI)',
    adminQuestionEn: 'Câu hỏi (EN)',
    adminSummaryVi: 'Tóm tắt (VI)',
    adminSummaryEn: 'Tóm tắt (EN)',
    adminBodyVi: 'Nội dung (VI)',
    adminBodyEn: 'Nội dung (EN)',
    adminTagVi: 'Tag (VI)',
    adminTagEn: 'Tag (EN)',
    adminConfirmDelete: 'Bạn có chắc muốn xoá bài viết này?',
    rss: 'RSS Feed',
    darkMode: 'Chế độ tối',
    lightMode: 'Chế độ sáng',
    loading: 'Đang tải...',
    loginError: 'Email hoặc mật khẩu không đúng',
  },
  en: {
    siteName: 'Immortality',
    siteTagline: 'Vietnamese Wisdom',
    heroTitle: 'Spaceship of Wisdom',
    heroSub: 'Discover the light within you — a healing journey from timeless Vietnamese wisdom',
    heroCta: 'Explore Now',
    topicsTitle: 'Topics',
    articlesTitle: 'Latest Articles',
    articles: 'articles',
    readMore: 'Read more',
    watchVideo: 'Watch video',
    back: '← Go back',
    videoPlaceholder: 'Video coming soon',
    searchTitle: 'Search',
    searchPlaceholder: 'Search by title, question...',
    noResults: 'No results found',
    contactTitle: 'Contact',
    contactName: 'Full name',
    contactEmail: 'Email',
    contactMsg: 'Message',
    contactSend: 'Send Message',
    contactThanks: 'Thank you! Your message has been sent.',
    footer: '© 2026 Immortality. Content is personal sharing and does not replace professional medical advice.',
    navHome: 'Home',
    navTopics: 'Topics',
    navSearch: 'Search',
    navContact: 'Contact',
    menuOpen: 'Menu',
    // New translations
    share: 'Share',
    copyLink: 'Copy link',
    copied: 'Copied!',
    comments: 'Comments',
    commentName: 'Your name',
    commentText: 'Write a comment...',
    commentSend: 'Send',
    commentEmpty: 'No comments yet. Be the first!',
    adminTitle: 'Manage Articles',
    adminLogin: 'Admin Login',
    adminEmail: 'Email',
    adminPassword: 'Password',
    adminSignIn: 'Sign In',
    adminSignOut: 'Sign Out',
    adminAdd: 'Add article',
    adminEdit: 'Edit',
    adminDelete: 'Delete',
    adminSave: 'Save',
    adminCancel: 'Cancel',
    adminTopic: 'Topic',
    adminTag: 'Tag',
    adminDate: 'Date',
    adminTitleVi: 'Title (VI)',
    adminTitleEn: 'Title (EN)',
    adminQuestionVi: 'Question (VI)',
    adminQuestionEn: 'Question (EN)',
    adminSummaryVi: 'Summary (VI)',
    adminSummaryEn: 'Summary (EN)',
    adminBodyVi: 'Body (VI)',
    adminBodyEn: 'Body (EN)',
    adminTagVi: 'Tag (VI)',
    adminTagEn: 'Tag (EN)',
    adminConfirmDelete: 'Are you sure you want to delete this article?',
    rss: 'RSS Feed',
    darkMode: 'Dark mode',
    lightMode: 'Light mode',
    loading: 'Loading...',
    loginError: 'Invalid email or password',
  },
}
